name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas numpy sqlite3 PyQt5 qtawesome reportlab 
    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --icon=logo.ico "GSYV ENVANTER SİSTEMİ.py"
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/GSYV ENVANTER SİSTEMİ.exe
        if-no-files-found: error  # Dosya bulunamazsa hata ver
