name: Build EXE and APP


on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas numpy PyQt5 qtawesome reportlab mplcursors openpyxl
    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --icon=logo.ico --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtCore --hidden-import=qtawesome --hidden-import=reportlab --add-data "DejaVuSans.ttf;." --add-data "Helvetica.ttf;." "GSYV.py"
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/GSYV.exe
        if-no-files-found: error  # Dosya bulunamazsa hata ver

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas numpy PyQt5 qtawesome reportlab mplcursors openpyxl
    - name: Build APP
      run: |
        pyinstaller --onefile --noconsole --icon=logo.icns --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtCore --hidden-import=qtawesome --hidden-import=reportlab --add-data "DejaVuSans.ttf:." --add-data "Helvetica.ttf:." "GSYV.py"
    - name: Upload APP
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/GSYV.app
        if-no-files-found: error  # Dosya bulunamazsa hata ver
